{% set name = "pedantic" %}
{% set version = "3.0.0" %}
{% set python_min = "3.11" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/pedantic-{{ version }}.tar.gz
  sha256: bd62f05548197c8946df7e0b3632b02a5a2c7a9a206048d05f870a5a2ec6de83

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - python {{ python_min }}
    - pip
    - setuptools
  run:
    - python >={{ python_min }}

test:
  imports:
    - pedantic
  commands:
    - pip check
  requires:
    - pip
    - python {{ python_min }}

about:
  home: https://github.com/LostInDarkMath/pedantic-python-decorators
  summary: Some useful Python decorators for cleaner software development.
  license: Apache-2.0
  license_file: LICENSE

extra:
  recipe-maintainers:
    - mikemhenry
