{% set name = "pedantic" %}
{% set version = "3.0.4" %}
{% set python_min = "3.11" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/pedantic-{{ version }}.tar.gz
  sha256: 0eaca93fb4fa8ca949b6a9da0a3a9458f4e2d4b58b345faa10eb27876efd7e15

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - python {{ python_min }}
    - pip
    - setuptools
  run:
    - python >={{ python_min }}
    - coverage >=7.14.0,<8.0.0

test:
  imports:
    - pedantic
  commands:
    - pip check
  requires:
    - pip
    - python {{ python_min }}

about:
  home: https://github.com/LostInDarkMath/pedantic-python-decorators
  summary: Some useful Python decorators for cleaner software development.
  license: Apache-2.0
  license_file: LICENSE

extra:
  recipe-maintainers:
    - mikemhenry
