{% set name = "pedantic" %}
{% set version = "2.3.3" %}
{% set python_min = "3.11" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/pedantic-{{ version }}.tar.gz
  sha256: 1341448708c6f215a8470e7dd33507b93a73b8f15cecca88c166bdb0f2cd8503

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - python {{ python_min }}
    - pip
    - setuptools
  run:
    - python >={{ python_min }}

test:
  imports:
    - pedantic
  commands:
    - pip check
  requires:
    - pip
    - python {{ python_min }}

about:
  home: https://github.com/LostInDarkMath/pedantic-python-decorators
  summary: Some useful Python decorators for cleaner software development.
  license: Apache-2.0
  license_file: LICENSE

extra:
  recipe-maintainers:
    - mikemhenry
